<!-- Generated by Gemini -->
<script>
	import { fade } from 'svelte/transition';
	export let isOpen = false;
</script>

<button
	on:click
	aria-label={isOpen ? 'Close menu' : 'Open menu'}
	aria-expanded={isOpen}
	class="hamburger-button"
>
	{#if isOpen}
		<div class="icon-wrapper" transition:fade={{ duration: 150 }}>
			<svg
				width="24"
				height="24"
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
			>
				<path
					d="M18 6L6 18"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				/>
				<path
					d="M6 6L18 18"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				/>
			</svg>
		</div>
	{:else}
		<div class="icon-wrapper" transition:fade={{ duration: 150 }}>
			<svg
				width="24"
				height="24"
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
			>
				<path
					d="M3 12H21"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				/>
				<path
					d="M3 6H21"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				/>
				<path
					d="M3 18H21"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				/>
			</svg>
		</div>
	{/if}
</button>

<style>
	.hamburger-button {
		background: none;
		border: none;
		padding: 8px; /* Adjust padding if needed for visual centering */
		cursor: pointer;
		color: #333;
		display: inline-flex; /* Changed from inline-flex to flex for better control over children */
		align-items: center;
		justify-content: center;
		transition: color 0.2s ease-in-out;
		position: relative; /* Crucial: Establishes a positioning context for absolute children */
		width: 40px; /* Example: Set a fixed width (24px icon + 8px padding * 2) */
		height: 40px; /* Example: Set a fixed height */
		box-sizing: border-box; /* Ensures padding is included in width/height */
	}

	.hamburger-button:hover {
		color: #555;
	}

	.icon-wrapper {
		position: absolute; /* Takes the wrapper out of normal flow */
		top: 50%; /* Center vertically */
		left: 50%; /* Center horizontally */
		transform: translate(-50%, -50%); /* Fine-tune centering */
		display: flex; /* Ensures SVG inside is aligned */
		align-items: center;
		justify-content: center;
	}
</style>
